ENH: Add actions to fetch data from BV-BRC.
bokulich-lab/RESCRIPt pull request #202
Opened 2024-08-20 14:15 UTC by VinzentRisch

solves #200 

- Adds new action fetch_genomes_bv_brc to fetch genome sequences outputted as GenomeData[DNASequences].
- Adds new action fetch_metadata_bv_brc to fetch any type of metadata outputted as immutable metadata.
- Adds new action fetch_taxonomy_bv_brc to fetch taxonomy data as FeatureData[Taxonomy].
- Adds new action fetch_genome_features_bv_brc to fetch genome feature sequences outputted as GenomeData[Genes] and GenomeData[Proteins].

- All actions make use of the [Data API](https://www.bv-brc.org/api/doc/) by BV-BRC. 
- The data that should be downloaded can be specified for all actions with an RQL style query. Additionally for the actions fetch_genomes_bv_brc, fetch_taxonomy_bv_brc and fetch_genome_features_bv_brc a list of IDs can be passed with an additional parameter for easier usage.

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/rescript.git
cd RESCRIPt
git fetch origin pull/102/head:pr-102
git checkout pr-102
pip install -e .
```

3. Test it out!
```bash
qiime rescript fetch-genomes-bv-brc --p-rql-query "in(genome_id,(224308.43,2030927.4755))" --output-dir genome_sequences
qiime rescript fetch-metadata-bv-brc --p-data-type genome --p-rql-query "in(genome_id,(224308.43,2030927.4755))" --output-dir metadata
qiime rescript fetch-taxonomy-bv-brc --p-rql-query "?in(taxon_id,(224308,2))" --output-dir taxonomy --p-ranks kingdom class phylum
qiime rescript fetch-genome-features-bv-brc --p-rql-query "in(genome_id,(2030927.4755))" --output-dir features
```

2024-08-20 21:57 UTC, mikerobeson commented
When I try and install this branch I obtain the following error:

> from q2_types.genome_data import GenomeData, Loci, Proteins, Genes, DNASequence
ImportError: cannot import name 'DNASequence' from 'q2_types.genome_data' (/home/.../.conda/envs/qiime2-amplicon-2024.5-test/lib/python3.9/site-packages/q2_types/genome_data/__init__.py)

I suggest that you merge this `get_bv_brc_data` branch with the latest version of the master / main branch the RESCRIPt repo. This PR is currently **3 commits behind the current branch**, and fails with the above error.

2024-08-21 11:17 UTC, VinzentRisch commented
Hi @mikerobeson 
I updated the branch. Now it should be ready to review.

2024-08-21 17:04 UTC, mikerobeson commented
I think there is still an issue. I am still unable to install the plugin and run `qiime --help`. When I do I get:

>from q2_types.genome_data import GenomeData, Loci, Proteins, Genes, DNASequence
ImportError: cannot import name 'DNASequence' from 'q2_types.genome_data' (/Users/.../AnalysisSoftware/miniconda3/envs/qiime2-amplicon-2024.5-test/lib/python3.9/site-packages/q2_types/genome_data/__init__.py)

2024-08-21 20:46 UTC, mikerobeson requested changes
Great start @VinzentRisch! I was able to run your example code via the dev version of QIIME 2.

There should be more content within the `parameter_descriptions` and `descriptions`. Also, it would be nice to have as part of your PR description, and the code help text / descriptions, the "use cases" for these actions. That is, what does a user do once they have these QZA files? How do they work with it? Perhaps consider constructing a RESCRIPt tutorial to eventually go along with this?

I'd also recommend swapping the names of your actions so that the name for the reference data is first: 

  - bv-brc-fetch-genome-features
  - bv-brc-fetch-genomes
  - bv-brc-fetch-metadata
  - bv-brc-fetch-taxonomy

2024-08-21 20:46 UTC, mikerobeson commented on rescript/plugin_setup.py
> +    description="Fetch BV-BCR metadata for a specific data type with an RQL "
Again, please provide a detailed description of what this action retrieves and what it outputs. What is the downstream use case for this? Can you provide an example?

2024-08-21 20:46 UTC, mikerobeson commented on rescript/plugin_setup.py
> +        'genome_ids': 'List of genome IDs from BV-BRC.',
Define and describe `rql_query` and `genome_ids`. For example, are the latter GenBank accessions?

2024-08-21 20:46 UTC, mikerobeson commented on rescript/plugin_setup.py
> +    description='Fetch taxonomy data from BV-BRC.',
Again, provide detailed description.

2024-08-21 20:49 UTC, mikerobeson commented on rescript/plugin_setup.py
> +    name='fetch genomes',
Should be consistent with the other names, and probably be something like `Fetch Genomes from BV-BRC`.

2024-09-13 12:01 UTC, VinzentRisch commented
Hi @mikerobeson 
- So I now removed the taxonomy action and added taxonomy outputs to the actions for genomes and genome features. I think having three actions makes it easy enough but still flexible to be specific with data querying.
- I added more options to query the data more effectively. 
- I have not yet added usage examples to the descriptions. I will come up with some examples on Monday during our dev meeting. Because I am not so sure myself what all can be done with this data in Qiime.

2024-10-01 19:06 UTC, mikerobeson commented
Hi @VinzentRisch,  I apologize for taking a while to get to this. 😬 

I really like to improvements. I was able to run everything w/o issue. Again, as I've never really used this tool, I'm not sure what the next steps are with the QZA outputs. Once I have an idea of what the "final" steps are I should be able to finalize my review. Other than that, nothing really stands out to me to fix.. at least for the moment. :-)

2024-10-02 12:41 UTC, mikerobeson commented
Thanks for that @nbokulich! I am okay to merge this as it is, if you think it is ready. I've nothing more to add. 👍

2024-10-03 15:47 UTC, merged